"""Tool for executing Node.js code snippets."""

from __future__ import annotations

import asyncio
import base64
import os
import shutil
import tempfile
import uuid
from pathlib import Path
from typing import Any

import structlog

from carbonclaw.core.base import BaseTool
from carbonclaw.core.models import ToolResult

logger = structlog.get_logger(__name__)


class RunNodeJSTool(BaseTool):
    """Executes Node.js code and returns stdout/stderr. Supports npm packages."""

    name = "run_nodejs"
    description = (
        "Executes a Node.js code snippet. "
        "Allows installing npm packages before execution. "
        "Can return a generated file as base64."
    )
    parameters = {
        "type": "object",
        "properties": {
            "code": {
                "type": "string",
                "description": "The Node.js source code to execute.",
            },
            "packages": {
                "type": "array",
                "items": {"type": "string"},
                "description": "Optional list of npm packages to install (e.g., ['pptxgenjs']).",
            },
            "output_file": {
                "type": "string",
                "description": "Optional path to a file generated by the code to be returned as base64.",
            },
        },
        "required": ["code"],
    }
    requires_approval = True

    async def execute(self, arguments: dict[str, Any]) -> ToolResult:
        code = arguments.get("code", "")
        packages = arguments.get("packages", [])
        output_file = arguments.get("output_file")

        if not code:
            return ToolResult(
                tool_call_id="",
                name=self.name,
                content="Error: No code provided.",
                is_error=True,
            )

        tmp_dir = Path(tempfile.gettempdir()) / f"carbonclaw_node_{uuid.uuid4().hex[:8]}"
        tmp_dir.mkdir(parents=True, exist_ok=True)
        
        script_path = tmp_dir / "script.js"
        script_path.write_text(code, encoding="utf-8")

        try:
            # 1. Install packages if any
            if packages:
                logger.info("nodejs.install_packages", packages=packages)
                pkg_cmd = ["npm", "install", "--prefix", str(tmp_dir)] + packages
                proc = await asyncio.create_subprocess_exec(
                    *pkg_cmd,
                    stdout=asyncio.subprocess.PIPE,
                    stderr=asyncio.subprocess.PIPE,
                )
                stdout, stderr = await proc.communicate()
                if proc.returncode != 0:
                    return ToolResult(
                        tool_call_id="",
                        name=self.name,
                        content=f"NPM Install Error:\n{stderr.decode()}",
                        is_error=True,
                    )

            # 2. Run script
            logger.info("nodejs.run_script", path=str(script_path))
            # Ensure we can find local modules
            env = os.environ.copy()
            env["NODE_PATH"] = str(tmp_dir / "node_modules")
            
            proc = await asyncio.create_subprocess_exec(
                "node",
                str(script_path),
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
                cwd=str(tmp_dir),
                env=env,
            )
            
            try:
                stdout_b, stderr_b = await asyncio.wait_for(proc.communicate(), timeout=60.0)
                stdout = stdout_b.decode(errors="replace")
                stderr = stderr_b.decode(errors="replace")
            except asyncio.TimeoutError:
                proc.kill()
                return ToolResult(
                    tool_call_id="",
                    name=self.name,
                    content="Error: Execution timed out after 60s.",
                    is_error=True,
                )

            # 3. Handle output file
            encoded_file = None
            if output_file:
                target_path = tmp_dir / output_file
                if target_path.exists():
                    data = target_path.read_bytes()
                    encoded_file = base64.b64encode(data).decode("utf-8")
                else:
                    stderr += f"\nWarning: Output file '{output_file}' not found."

            combined_out = f"STDOUT:\n{stdout}\n\nSTDERR:\n{stderr}"
            if encoded_file:
                combined_out += f"\n\n[FILE:{output_file}]\n{encoded_file}"

            return ToolResult(
                tool_call_id="",
                name=self.name,
                content=combined_out,
                is_error=proc.returncode != 0,
            )

        except Exception as e:
            logger.exception("nodejs.execution_failed")
            return ToolResult(
                tool_call_id="",
                name=self.name,
                content=f"Unexpected error: {str(e)}",
                is_error=True,
            )
        finally:
            shutil.rmtree(tmp_dir, ignore_errors=True)
